export {default as Home} from './Home/Home'
export {default as Login} from './Auth/Login'
export {default as Registration} from './Auth/Registration'
export {default as Cart} from './cart/Cart'
export {default as ProductShow} from './Product/ProductShow'
export {default as ProductDetails} from './Product/ProductDetails'
export {default as Review} from './Review/Review'